### ISSUE TITLE
https://api.npmjs.org/

### ISSUE THREAD

**Issue by mesaugat** [npm/download-counts#32]
https://api.npmjs.org/ is returning a stack trace as a response. I don't think it should be doing that in production.

```json
{"message":"Not Found","stack":"Error: Not Found\n    at runProcessView (/mnt/deploys/redis-download-counts/node_modules/@npm/knork/knork.js:162:11)\n    at runProcessRequest.then.userResponse (/mnt/deploys/redis-download-counts/node_modules/@npm/knork/knork.js:104:16)\n    at bound (domain.js:280:14)\n    at runBound (domain.js:293:12)\n    at tryCatcher (/mnt/deploys/redis-download-counts/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/mnt/deploys/redis-download-counts/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/mnt/deploys/redis-download-counts/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/mnt/deploys/redis-download-counts/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/mnt/deploys/redis-download-counts/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/mnt/deploys/redis-download-counts/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/mnt/deploys/redis-download-counts/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/mnt/deploys/redis-download-counts/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:666:20)\n    at tryOnImmediate (timers.js:639:5)\n    at processImmediate [as _immediateCallback] (timers.js:611:5)"}
```

**Comment by bcoe** [comment]
@mesaugat this is now fixed.
